### ISSUE TITLE
has no category

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.z.Cumulonimbus#1]
![captura de tela de 2017-12-21 19-38-34](https://user-images.githubusercontent.com/26097419/34276104-1091cfa0-e687-11e7-8e86-4727badacafd.png)

**Comment by TingPing** [comment]
This uses the upstream desktop file so that should be reported there.

**Comment by nedrichards** [comment]
This was fixed in 1.9.3 upstream so it should be included in the next stable release that flathub gets.
