### ISSUE TITLE
update to 1.28.0, add auto update and rername package to com.github.z.cpod

### ISSUE THREAD

**Issue by LeSnake04** [flathub/com.github.z.Cumulonimbus#11]
1. There is a new version: https://github.com/z-------------/CPod/releases/tag/v1.28.0
2. We should add auto update
3. maybe rename this package to com.github.z.cpod, since it was renamed years ago

I can help with auto update and updating the package.

**Comment by hfiguiere** [comment]
renaming the package require resubmitting it.

**Comment by lionirdeadman** [comment]
Considering the release notes, I'd personally opt to update it one last time and then EOL it because as the other says - it is not maintained anymore.

**Comment by LeSnake04** [comment]
Tough there are commits last month, so releases may come in the future.

So auto update will make sense and is easy to set up.

But yeah, renaming it might be too much trouble until its actively worked on.

**Comment by LeSnake04** [comment]
@hfiguiere Can you please review?
