### ISSUE TITLE
Update CPod (Cumulonimbus) to to 1.23.1?

### ISSUE THREAD

**Issue by ghost** [flathub/com.github.z.Cumulonimbus#6]
The app has changed its name and logo. The GitHub repo name has remained the same. See https://github.com/z-------------/cumulonimbus/releases/tag/v1.14.0 .

**Comment by superusercode** [comment]
@nedrichards How is this to be updated if the name has changed? Wouldn't some hard-coded values need to change as well?

**Comment by nedrichards** [comment]
So long as the appid remains the same for now - it'll be seen as the same app. We can change the name within the files easily - this will be slightly confusing on the command line for now - but CLI users aren't the primary target.

**Comment by nedrichards** [comment]
Otherwise - this depends on the same fix as https://github.com/flathub/org.filezillaproject.Filezilla/issues/2 and a few other apps - the ability to rename an app inside flathub

**Comment by Lvaskz** [comment]
There is New versión 1.15 and New name and icon

**Comment by jgarciao** [comment]
One option could be to retire this app and publish CPod as a new one with the new name

**Comment by bilelmoussaoui** [comment]
@nedrichards what shall we do in this case? Should we EOL this app?

 We can migrate app-id to a new one, but an upstream maintainer/collaborator has to submit it

**Comment by lionirdeadman** [comment]
This has been fixed with #10, should be closed.
